//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umea_rana.LocalizedStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umea_rana.LocalizedStrings.LocalizedString", typeof(LocalizedString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ennemy Alignment.
        /// </summary>
        internal static string AI_align {
            get {
                return ResourceManager.GetString("AI_align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allen.
        /// </summary>
        internal static string allen {
            get {
                return ResourceManager.GetString("allen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string angle {
            get {
                return ResourceManager.GetString("angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asteroid.
        /// </summary>
        internal static string Asteroid {
            get {
                return ResourceManager.GetString("Asteroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        internal static string Background_image {
            get {
                return ResourceManager.GetString("Background_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Speed.
        /// </summary>
        internal static string Background_speed {
            get {
                return ResourceManager.GetString("Background_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        internal static string bomb {
            get {
                return ResourceManager.GetString("bomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string bonus {
            get {
                return ResourceManager.GetString("bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss.
        /// </summary>
        internal static string Boss {
            get {
                return ResourceManager.GetString("Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss life.
        /// </summary>
        internal static string BossLife {
            get {
                return ResourceManager.GetString("BossLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet&apos;s Color.
        /// </summary>
        internal static string Bullet_Color {
            get {
                return ResourceManager.GetString("Bullet_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet Speed.
        /// </summary>
        internal static string Bullet_speed {
            get {
                return ResourceManager.GetString("Bullet_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss.
        /// </summary>
        internal static string choix_boss {
            get {
                return ResourceManager.GetString("choix_boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comet.
        /// </summary>
        internal static string Comet {
            get {
                return ResourceManager.GetString("Comet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string cred {
            get {
                return ResourceManager.GetString("cred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this video game is presented by Umea-rana team.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string easy {
            get {
                return ResourceManager.GetString("easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ennemis.
        /// </summary>
        internal static string ennemis {
            get {
                return ResourceManager.GetString("ennemis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are friend.
        /// </summary>
        internal static string equality {
            get {
                return ResourceManager.GetString("equality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinpatsu.
        /// </summary>
        internal static string eve {
            get {
                return ResourceManager.GetString("eve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Directory.
        /// </summary>
        internal static string existing_directory {
            get {
                return ResourceManager.GetString("existing_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        internal static string Extreme {
            get {
                return ResourceManager.GetString("Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        internal static string Finnish {
            get {
                return ResourceManager.GetString("Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.P.M.
        /// </summary>
        internal static string Firerate {
            get {
                return ResourceManager.GetString("Firerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string Full_screen {
            get {
                return ResourceManager.GetString("Full_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highscore: your are very good gamer.
        /// </summary>
        internal static string good_gamer {
            get {
                return ResourceManager.GetString("good_gamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your are a very good gamer.
        /// </summary>
        internal static string goodgame {
            get {
                return ResourceManager.GetString("goodgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero.
        /// </summary>
        internal static string hero {
            get {
                return ResourceManager.GetString("hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Score.
        /// </summary>
        internal static string Highscore {
            get {
                return ResourceManager.GetString("Highscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maison.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        internal static string Image_file {
            get {
                return ResourceManager.GetString("Image_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflicted Damage.
        /// </summary>
        internal static string inficted_damage {
            get {
                return ResourceManager.GetString("inficted_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to japanese.
        /// </summary>
        internal static string japanese {
            get {
                return ResourceManager.GetString("japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamikaze.
        /// </summary>
        internal static string Kamikaze {
            get {
                return ResourceManager.GetString("Kamikaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Name.
        /// </summary>
        internal static string level_name {
            get {
                return ResourceManager.GetString("level_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life.
        /// </summary>
        internal static string Life {
            get {
                return ResourceManager.GetString("Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Editor.
        /// </summary>
        internal static string Map_Editor {
            get {
                return ResourceManager.GetString("Map_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile.
        /// </summary>
        internal static string missile {
            get {
                return ResourceManager.GetString("missile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateforme Mobile.
        /// </summary>
        internal static string mob_plat {
            get {
                return ResourceManager.GetString("mob_plat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        internal static string Multiplayer {
            get {
                return ResourceManager.GetString("Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string music {
            get {
                return ResourceManager.GetString("music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Files.
        /// </summary>
        internal static string Music_file {
            get {
                return ResourceManager.GetString("Music_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noir &amp; Blanc.
        /// </summary>
        internal static string n_et_b {
            get {
                return ResourceManager.GetString("n_et_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rusco.
        /// </summary>
        internal static string naruto {
            get {
                return ResourceManager.GetString("naruto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Kamikazes.
        /// </summary>
        internal static string nb_IAK {
            get {
                return ResourceManager.GetString("nb_IAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Shooters.
        /// </summary>
        internal static string nb_iaT {
            get {
                return ResourceManager.GetString("nb_iaT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Snipers.
        /// </summary>
        internal static string nb_iaV {
            get {
                return ResourceManager.GetString("nb_iaV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of U.F.O.
        /// </summary>
        internal static string nb_objet {
            get {
                return ResourceManager.GetString("nb_objet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Alexis Yang
        ///Kamwa Watanabe Bjay alias Akai-Suisei
        ///Anne Constance Remy-Neris.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highscore: P1 is the best, p2 is a looser.
        /// </summary>
        internal static string p1best {
            get {
                return ResourceManager.GetString("p1best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1 Win.
        /// </summary>
        internal static string p1win {
            get {
                return ResourceManager.GetString("p1win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highscore: P2 is the best, p1 is a looser.
        /// </summary>
        internal static string p2best {
            get {
                return ResourceManager.GetString("p2best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2 Win.
        /// </summary>
        internal static string p2win {
            get {
                return ResourceManager.GetString("p2win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string PLA {
            get {
                return ResourceManager.GetString("PLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateformes.
        /// </summary>
        internal static string plateformes {
            get {
                return ResourceManager.GetString("plateformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Life.
        /// </summary>
        internal static string player_life {
            get {
                return ResourceManager.GetString("player_life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        internal static string Replay {
            get {
                return ResourceManager.GetString("Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save/Apply.
        /// </summary>
        internal static string save_apply {
            get {
                return ResourceManager.GetString("save_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolling.
        /// </summary>
        internal static string ScrollingVertical {
            get {
                return ResourceManager.GetString("ScrollingVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Item.
        /// </summary>
        internal static string Selected_item {
            get {
                return ResourceManager.GetString("Selected_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot&apos;em Up.
        /// </summary>
        internal static string SEU {
            get {
                return ResourceManager.GetString("SEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooteur.
        /// </summary>
        internal static string Shooter {
            get {
                return ResourceManager.GetString("Shooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        internal static string Sniper {
            get {
                return ResourceManager.GetString("Sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateforme Stable.
        /// </summary>
        internal static string stab_plat {
            get {
                return ResourceManager.GetString("stab_plat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string terminated {
            get {
                return ResourceManager.GetString("terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajectory.
        /// </summary>
        internal static string Trajectory {
            get {
                return ResourceManager.GetString("Trajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemon Lucifer.
        /// </summary>
        internal static string Tuc {
            get {
                return ResourceManager.GetString("Tuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.F.O.
        /// </summary>
        internal static string UFO {
            get {
                return ResourceManager.GetString("UFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume BGM.
        /// </summary>
        internal static string Volume_BGM {
            get {
                return ResourceManager.GetString("Volume_BGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGM volume.
        /// </summary>
        internal static string Volume_effet_sonore {
            get {
                return ResourceManager.GetString("Volume_effet_sonore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoh.
        /// </summary>
        internal static string yoh {
            get {
                return ResourceManager.GetString("yoh", resourceCulture);
            }
        }
    }
}
